plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    id("com.google.gms.google-services")
}

android {
    namespace 'com.example.outfitcoordination'
    compileSdk 36

    defaultConfig {
        applicationId "com.example.outfitcoordination"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }

    buildFeatures{
        viewBinding = true
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:33.9.0')
    implementation 'com.google.firebase:firebase-auth' // authentication
    implementation 'com.google.firebase:firebase-firestore' // firestore database
    implementation 'com.google.firebase:firebase-storage' // save image
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.7.3' //coroutine
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0' // viewmodel
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.7.0' //livedata
    implementation 'androidx.fragment:fragment-ktx:1.8.6'
    implementation "com.squareup.retrofit2:retrofit:2.9.0" //retrofit
    implementation "com.squareup.retrofit2:converter-gson:2.9.0" //gson
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.7.0"
    implementation "com.github.bumptech.glide:glide:4.16.0"
    implementation 'com.cloudinary:cloudinary-android:2.5.0'
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.activity
    implementation libs.androidx.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core

    // AndroidX
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.coordinatorlayout:coordinatorlayout:1.2.0'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'androidx.cardview:cardview:1.0.0'

    // Material Design
    implementation 'com.google.android.material:material:1.11.0'

    // ViewPager2 (cho banner)
    implementation 'androidx.viewpager2:viewpager2:1.0.0'

    // Glide (load ảnh)
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'

    // CircleImageView (avatar tròn)
    implementation 'de.hdodenhof:circleimageview:3.1.0'
}